project:
  type: book

book:

  # navbar:
  #   background: primary
  #   search: true
  #   left:
  #     - text: "Home"
  #       href: index.qmd
  sidebar:
    style: "docked"
    search: true
    type: "dark"
  title: "Entanglement Diagnostics in Solids"
  author: "Samuel Hopkins"
  date: "10/29/2024"
  chapters:
    - index.qmd
    - part: part/condmat/condmat.qmd
      chapters:
      - part/condmat/secondquant.qmd
      - part/condmat/metal.qmd
      - part/condmat/bcs.qmd
      - part/condmat/hubbard.qmd
    - part: part/bgtheory/bgtheory.qmd
      chapters:
      - part/bgtheory/linresp.qmd
      - part/bgtheory/opticalcond.qmd
      - part/bgtheory/entanglement.qmd
      - part/bgtheory/measures.qmd
    - part: part/coretheo/coretheo.qmd
      chapters:
      - part/coretheo/qfi.qmd
      - part/coretheo/qvar.qmd
    - part: part//method/methods.qmd
      chapters:
      - part/method/tennet.qmd
    - summary.qmd
    - references.qmd
bibliography: references.bib

format:
  html:
    theme: lumen
    fontsize: 0.95em

  pdf:
    documentclass: scrreprt



